[debug] [2025-04-07T11:03:47.778Z] ----------------------------------------------------------------------
[debug] [2025-04-07T11:03:47.807Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\kaito\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2025-04-07T11:03:47.808Z] CLI Version:   14.1.0
[debug] [2025-04-07T11:03:47.809Z] Platform:      win32
[debug] [2025-04-07T11:03:47.809Z] Node Version:  v22.13.1
[debug] [2025-04-07T11:03:47.811Z] Time:          Mon Apr 07 2025 12:03:47 GMT+0100 (GMT+01:00)
[debug] [2025-04-07T11:03:47.811Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-04-07T11:03:48.070Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-04-07T11:03:48.071Z] > authorizing via signed-in user (kaitokid0110@gmail.com)
[debug] [2025-04-07T11:03:48.071Z] [iam] checking project fir-fec62 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2025-04-07T11:03:48.072Z] Checked if tokens are valid: false, expires at: 1744023868853
[debug] [2025-04-07T11:03:48.072Z] Checked if tokens are valid: false, expires at: 1744023868853
[debug] [2025-04-07T11:03:48.072Z] > refreshing access token with scopes: []
[debug] [2025-04-07T11:03:48.074Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-04-07T11:03:48.074Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-04-07T11:03:53.676Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------512766224801891089191552","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo EAI_AGAIN www.googleapis.com
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-04-07T11:03:53.679Z] [iam] error while checking permissions, command may fail: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-04-07T11:03:53.682Z] Checked if tokens are valid: false, expires at: 1744023868853
[debug] [2025-04-07T11:03:53.683Z] Checked if tokens are valid: false, expires at: 1744023868853
[debug] [2025-04-07T11:03:53.683Z] > refreshing access token with scopes: []
[debug] [2025-04-07T11:03:53.684Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-04-07T11:03:53.684Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-04-07T11:03:53.702Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------345648277345142115817638","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo EAI_AGAIN www.googleapis.com
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-04-07T11:03:53.703Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-04-07T11:03:58.741Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\kaito\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
